name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Test script
      run: |
        curl https://raw.githubusercontent.com/webmsgr/getv/master/getv.sh | sh
